### PR TITLE
Fixed styling issues due to upgrade

### LINKED ISSUE #11: Investigate styling issues after vulnerable package upgrades
See #9 for details. Related to issue #4 .

### PR DESCRIPTION
**Pull request by anasdeis**
closes #11

### CODE REVIEW

File: utils/WebpackGenerator.js [hunk 1]
```diff
@@ -26,11 +26,14 @@ module.exports = {\n\
...
-                    }\n\
+                  {\n\
+                    loader: 'style-loader'\n\
+                  },\n\
+                  {\n\
+                    loader: 'css-loader'\n\
+                  }\n\
                 ]\n\
-            },\n\
+              },\n\
```
Comment (klaframboise) [inline utils/WebpackGenerator.js]: Remove extra whitespace

Comment (anasdeis) [reply utils/WebpackGenerator.js]: Fixed it!
